export const products = [
    {
        name: 'Frying Pan',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/494241084/crisera-grey-non-stick-induction-bottom-fry-pan-24-cm-product-images-o494241084-p604746118-0-202309221837.jpg?im=Resize=(360,360)',
        price: '₹2,000',
        link: 'https://www.amazon.in/s?k=frying-pan',
    },
    {
        name: 'Pressure Cooker',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/494460683/de-prism-aluminium-outer-lid-3-l-non-induction-base-pressure-cooker-bis-certified-product-images-o494460683-p609660165-0-202408061839.jpg?im=Resize=(360,360)',
        price: '₹2,500',
        link: 'https://www.amazon.in/s?k=pressure-cooker',
    },
    {
        name: 'Blender',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/rv7mw31xgo/induxin-hand-blender-mixer-froth-whisker-lassi-maker-for-lassi-curd-milk-coffee-egg-beater-50-w-hand-blender-multi-product-images-orv7mw31xgo-p604306405-0-202309011432.jpg?im=Resize=(360,360)',
        price: '₹2,500',
        link: 'https://www.amazon.in/s?k=blender',
    },
    {
        name: 'Kitchen Knife',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/rvrt484jwi/szonz-8-piece-knife-set-stainless-steel-kitchenware-stainless-steel-kitchen-knife-set-8-pieces-with-scissor-peeler-knives-sharper-product-images-orvrt484jwi-p605442363-0-202310041950.jpg?im=Resize=(360,360)',
        price: '₹200',
        link: 'https://www.amazon.in/s?k=kitchen-knife',
    },
    {
        name: 'Colander',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/rv6u4tzddn/hazel-stainless-steel-strainer-basket-without-handle-steet-fruits-basket-vegetable-basket-for-kitchen-washer-colander-sieve-for-kitchen-16-5-cm-product-images-orv6u4tzddn-p596910692-0-202301032301.jpg?im=Resize=(360,360)',
        price: '₹150',
        link: 'https://www.amazon.in/s?k=colander',
    },
    {
        name: 'Spice Rack',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/rvuhj5r71l/pacificsurf-360-degree-revolving-shape-transparent-spice-rack-container-spice-stand-for-kitchen-storage-container-rack-sets-spice-racks-containers-namak-dani-tikka-pepper-oregano-16in1-product-images-orvuhj5r71l-p599596568-0-202303190547.jpg?im=Resize=(360,360)',
        price: '₹500',
        link: 'https://www.amazon.in/s?k=spice-rack',
    },
    {
        name: 'Cooking Pot',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/490062451/hawkins-futura-cook-n-serve-black-hard-anodised-stew-pot-8-5-l-product-images-o490062451-p604549656-0-202309121539.jpg?im=Resize=(360,360)',
        price: '₹800',
        link: 'https://www.amazon.in/s?k=cooking-pot',
    },
    {
        name: 'Baking Sheet',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/rvvrxm8hnu/avmphd-silicon-roti-mat-non-stick-silicone-reusable-pastry-fondant-dough-roti-chapati-rolling-baking-sheet-mat-with-measurements-50-40-cm-multicolor-product-images-orvvrxm8hnu-p601732355-0-202305232118.jpg?im=Resize=(360,360)',
        price: '₹400',
        link: 'https://www.amazon.in/s?k=baking-sheet',
    },
    {
        name: 'Muffin Tin',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/rvlmke2qjd/moldberry-muffin-tin-tray-12-slot-mini-midi-shape-cupcake-mould-for-microwave-oven-tin-baking-tray-1-product-images-orvlmke2qjd-p602080872-0-202306021209.jpg?im=Resize=(360,360)',
        price: '₹300',
        link: 'https://www.amazon.in/s?k=muffin-tin',
    },
    {
        name: 'Measuring Cups',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/rvf1nqdiqg/k-kudos-enterprise-assorted-plastic-measuring-cups-and-spoons-set-of-8-product-images-orvf1nqdiqg-p600890631-0-202304251034.jpg?im=Resize=(360,360)',
        price: '₹250',
        link: 'https://www.amazon.in/s?k=measuring-cups',
    },
    {
        name: 'Wooden Spoons',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/rvuxtwmaez/shopimoz-wooden-spoons-and-spatula-for-cooking-sleek-sold-and-non-stick-heavy-pack-of-7-product-images-orvuxtwmaez-p596595633-0-202212231245.jpg?im=Resize=(360,360)',
        price: '₹200',
        link: 'https://www.amazon.in/s?k=wooden-spoons',
    },
    {
        name: 'Silicone Spatula',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/rvrgtclsxv/creative-zone-6-pcs-spetulas-kitchen-tool-set-silicon-spatula-nylon-heat-resistant-nonstick-serving-spoon-spatula-pasta-server-deep-ladle-turner-scoop-kitchen-serving-utensil-tools-spoon-spatula-turner-cooking-baking-tool-kitchen-utensil-set-product-images-orvrgtclsxv-p609654206-0-202408051852.jpg?im=Resize=(360,360)',
        price: '₹150',
        link: 'https://www.amazon.in/s?k=silicone-spatula',
    },
    {
        name: 'Kitchen Shears',
        category: 'Kitchen Essentials',
        image: 'https://www.jiomart.com/images/product/original/rvopzy1esp/kitchub-handy-chopper-xl-vegetable-fruit-nut-onion-chopper-hand-meat-grinder-mixer-food-processor-slicer-shredder-salad-maker-vegetable-tools-product-images-orvopzy1esp-p606783118-0-202312182026.jpg?im=Resize=(360,360)',
        price: '₹100',
        link: 'https://www.amazon.in/s?k=kitchen-shears',
    },
    {
        name: 'Rice (Chawal)',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/491638884/daawat-devaaya-everyday-rice-5-kg-product-images-o491638884-p491638884-0-202203151831.jpg?im=Resize=(360,360)',
        price: '₹50',
        link: 'https://www.amazon.in/s?k=rice',
    },
    {
        name: 'Wheat (Gehu)',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/rvquelkoov/gropure-organic-wheat-sharbati-4-5kg-product-images-orvquelkoov-p598401261-0-202302151001.jpg?im=Resize=(360,360)',
        price: '₹60',
        link: 'https://www.amazon.in/s?k=wheat',
    },
    {
        name: 'Oats',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/490710232/saffola-natural-creamy-oats-1-kg-free-300-g-pack-product-images-o490710232-p490710232-0-202402180804.jpg?im=Resize=(360,360)',
        price: '₹70',
        link: 'https://www.amazon.in/s?k=oats',
    },
    {
        name: 'Barley (Jau)',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/rvel794hlk/trinetra-best-quality-barley-whole-1kg-pack-of-1-jau-sabut-1000-g-product-images-orvel794hlk-p591503841-0-202205220000.jpg?im=Resize=(360,360)',
        price: '₹80',
        link: 'https://www.amazon.in/s?k=barley',
    },
    {
        name: 'Corn (Makka)',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/rvkrmgo4ru/okhli-musal-brand-corn-sabut-indian-makki-maize-millet-makka-maize-superfine-makki-dana-whole-grain-sabut-960g-480g-2pkt-product-images-orvkrmgo4ru-p596448133-0-202301301043.png?im=Resize=(360,360)',
        price: '₹90',
        link: 'https://www.amazon.in/s?k=corn',
    },
    {
        name: 'Quinoa',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/rvw2f4ssz4/goshudh-quinoa-1kg-pack-of-1-quinoa-seed-1000-g-product-images-orvw2f4ssz4-p600789676-0-202304212009.jpg?im=Resize=(360,360)',
        price: '₹120',
        link: 'https://www.amazon.in/s?k=quinoa',
    },
    {
        name: 'Buckwheat',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/rvdtcffkzn/90-s-mill-buckwheat-kuttu-atta-pseudocereal-flour-kuttu-ka-atta-shivratri-navaratri-janmashtami-flour-240gm-1pkt-product-images-orvdtcffkzn-p596558115-0-202301301259.png?im=Resize=(360,360)',
        price: '₹150',
        link: 'https://www.amazon.in/s?k=buckwheat',
    },
    {
        name: 'Millet',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/rvwbnlajxz/farmbean-barnyard-millet-natural-grains-1kg-khira-swank-kuthiraivally-udalu-kodisama-siridhanya-native-low-gi-millet-rice-high-protein-100-more-fibre-than-rice-1000-g-product-images-orvwbnlajxz-p593788839-0-202209152051.jpg?im=Resize=(360,360)',
        price: '₹180',
        link: 'https://www.amazon.in/s?k=millet',
    },
    {
        name: 'Sorghum (Jowar)',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/rvavq0zxqj/farmbean-whole-white-jowar-grains-1-kg-sorghum-jonna-for-weight-loss-native-low-gi-millet-rice-high-protein-100-more-fibre-than-rice-1000g-product-images-orvavq0zxqj-p593793045-0-202209152237.jpg?im=Resize=(420,420)',
        price: '₹200',
        link: 'https://www.amazon.in/s?k=sorghum',
    },
    {
        name: 'Teff',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/rvhs8qvimz/nourish-you-teff-flour-500-g-vegan-organic-gluten-free-improves-gut-health-rich-in-micro-nutrients-no-preservatives-whole-grain-teff-flour-pack-of-1-product-images-orvhs8qvimz-p594438657-0-202308241747.jpg?im=Resize=(360,360)',
        price: '₹220',
        link: 'https://www.amazon.in/s?k=teff',
    },
    {
        name: 'Amaranth (Chaulai)',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/rvhviiqfda/health-fields-organic-amaranth-millet-chaulai-millet-1kg-product-images-orvhviiqfda-p607819255-0-202402071938.jpg?im=Resize=(360,360)',
        price: '₹250',
        link: 'https://www.amazon.in/s?k=amaranth',
    },
    {
        name: 'Spelt ',
        category: 'Cereals',
        image: 'https://www.jiomart.com/images/product/original/rvyvaf3wm9/goshudh-best-quality-vitamin-spelt-wheat-atta-1kg-pack-of-1-vitamin-spelt-wheat-flour-1000-g-product-images-orvyvaf3wm9-p591365933-0-202205162036.jpg?im=Resize=(360,360)',
        price: '₹300',
        link: 'https://www.amazon.in/s?k=spelt',
    },
    {
        name: 'Turmeric (Haldi)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/490870053/catch-turmeric-powder-200-g-product-images-o490870053-p490870053-0-202203171023.jpg?im=Resize=(360,360)',
        price: '₹50',
        link: 'https://www.amazon.in/s?k=turmeric',
    },
    {
        name: 'Coriander (Dhaniya)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rv0lkngilk/notlih-whole-coriander-seeds-500gm-sabut-dhania-product-images-orv0lkngilk-p595320415-0-202211150917.png?im=Resize=(360,360)',
        price: '₹60',
        link: 'https://www.amazon.in/s?k=coriander',
    },
    {
        name: 'Cumin (Jeera)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/491185109/good-life-jeera-100-g-product-images-o491185109-p491185109-0-202306131531.jpg?im=Resize=(360,360)',
        price: '₹70',
        link: 'https://www.amazon.in/s?k=cumin',
    },
    {
        name: 'Red Chili Powder',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/490069979/catch-red-chilli-powder-100-g-product-images-o490069979-p490069979-0-202203170514.jpg?im=Resize=(360,360)',
        price: '₹80',
        link: 'https://www.amazon.in/s?k=red-chili-powder',
    },
    {
        name: 'Garam Masala',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rvdmbprzdi/freshocartz-organic-whole-sabut-garam-masala-100-g-product-images-orvdmbprzdi-p602890368-0-202307012353.jpg?im=Resize=(360,360)',
        price: '₹90',
        link: 'https://www.amazon.in/s?k=garam-masala',
    },
    {
        name: 'Ginger Powder (Adrak)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rvmrxk6pdd/urban-platter-dried-ginger-powder-sunth-80g-product-images-orvmrxk6pdd-p602310862-0-202306101704.jpg?im=Resize=(360,360)',
        price: '₹100',
        link: 'https://www.amazon.in/s?k=ginger-powder',
    },
    {
        name: 'Clove (Laung)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/493646079/good-life-cloves-laung-15-g-product-images-o493646079-p600873861-0-202304242038.jpg?im=Resize=(360,360)',
        price: '₹120',
        link: 'https://www.amazon.in/s?k=clove',
    },
    {
        name: 'Cardamom (Elaichi)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rvc4aawukh/marwar-green-cardamom-hari-choti-elaichi-whole-100grams-product-images-orvc4aawukh-p592116417-0-202206181802.jpg?im=Resize=(360,360)',
        price: '₹150',
        link: 'https://www.amazon.in/s?k=cardamom',
    },
    {
        name: 'Cinnamon (Dalchini)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rvd8tlhsej/goshudh-best-quality-dal-chini-100gm-pack-of-1-cinnamon-stick-100-g-product-images-orvd8tlhsej-p591424196-0-202205181104.jpg?im=Resize=(420,420)',
        price: '₹180',
        link: 'https://www.amazon.in/s?k=cinnamon',
    },
    {
        name: 'Black Pepper (Kali Mirch)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rvln7jftc5/surya-100g-black-pepper-kali-mirchi-whole-authentic-spices-masala-product-images-orvln7jftc5-p598181369-0-202406261746.jpg?im=Resize=(360,360)',
        price: '₹200',
        link: 'https://www.amazon.in/s?k=black-pepper',
    },
    {
        name: 'Fenugreek (Methi)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rv4paav35x/goshudh-best-quality-dana-methi-500gm-pack-of-1-fenugreek-seed-500-g-product-images-orv4paav35x-p591425674-0-202205181224.jpg?im=Resize=(360,360)',
        price: '₹220',
        link: 'https://www.amazon.in/s?k=fenugreek',
    },
    {
        name: 'Mustard Seeds (Rai or Sarson)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rvk6htozoj/urban-platter-whole-black-mustard-seeds-rai-or-sarson-shaker-jar-600g-21-1oz-product-images-orvk6htozoj-p601284953-0-202305090551.jpg?im=Resize=(360,360)',
        price: '₹250',
        link: 'https://www.amazon.in/s?k=mustard-seeds',
    },
    {
        name: 'Fennel Seeds (Sauf)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rvxcawc2go/foodcan-fennel-seeds-small-thin-green-barik-saunf-lucknowi-sounf-for-mouth-freshener-400-gram-pack-product-images-orvxcawc2go-p593518810-0-202208280826.png?im=Resize=(360,360)',
        price: '₹280',
        link: 'https://www.amazon.in/s?k=fennel-seeds',
    },
    {
        name: 'Carom Seeds (Ajwain)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rvkd4zvb0c/trinetra-best-quality-ajwain-100gm-pack-of-1-carom-seed-100-g-product-images-orvkd4zvb0c-p591371213-0-202205170203.jpg?im=Resize=(360,360)',
        price: '₹300',
        link: 'https://www.amazon.in/s?k=carom-seeds',
    },
    {
        name: 'Asafoetida (Hing)',
        category: 'Spices',
        image: 'https://www.jiomart.com/images/product/original/rvu5tiefj7/organic-purify-asafoetida-hing-powder-50gm-product-images-orvu5tiefj7-p599204513-0-202303101620.jpg?im=Resize=(360,360)',
        price: '₹350',
        link: 'https://www.amazon.in/s?k=asafoetida',
    },
    {
        name: 'Onion',
        category: 'Vegetables',
        image: 'https://www.jiomart.com/images/product/original/590003515/onion-1-kg-product-images-o590003515-p590003515-0-202408070949.jpg?im=Resize=(360,360)',
        price: '₹20',
        link: 'https://www.amazon.in/s?k=onion',
    },
    {
        name: 'Potato',
        category: 'Vegetables',
        image: 'https://www.jiomart.com/images/product/original/590001788/nutrafresh-potato-low-sugar-2-kg-product-images-o590001788-p590001788-0-202408132027.jpg?im=Resize=(360,360)',
        price: '₹25',
        link: 'https://www.amazon.in/s?k=potato',
    },
    {
        name: 'Tomato',
        category: 'Vegetables',
        image: 'https://www.jiomart.com/images/product/original/590003517/tomato-1-kg-product-images-o590003517-p590003517-0-202408091800.jpg?im=Resize=(360,360)',
        price: '₹30',
        link: 'https://www.amazon.in/s?k=tomato',
    },
    {
        name: 'Cucumber',
        category: 'Vegetables',
        image: 'https://i.pinimg.com/236x/59/f4/f9/59f4f9e18bbaa9c4c75a06be4ce19bde.jpg',
        price: '₹35',
        link: 'https://www.amazon.in/s?k=cucumber',
    },
    {
        name: 'Carrot',
        category: 'Vegetables',
        image: 'https://www.jiomart.com/images/product/original/590003546/carrot-orange-500-g-product-images-o590003546-p590003546-0-202408070949.jpg?im=Resize=(360,360)',
        price: '₹40',
        link: 'https://www.amazon.in/s?k=carrot',
    },
    {
        name: 'Beetroot',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/71XsyPm+xZL._AC_UL320_.jpg',
        price: '₹45',
        link: 'https://www.amazon.in/s?k=beetroot',
    },
    {
        name: 'Broccoli',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/51-FJIdimCL._AC_UL320_.jpg',
        price: '₹50',
        link: 'https://www.amazon.in/s?k=broccoli',
    },
    {
        name: 'Cauliflower',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/51BomV2ZiaL._AC_UL320_.jpg',
        price: '₹55',
        link: 'https://www.amazon.in/s?k=cauliflower',
    },
    {
        name: 'Spinach',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/71hHgpU0+yL._AC_UL320_.jpg',
        price: '₹60',
        link: 'https://www.amazon.in/s?k=spinach',
    },
    {
        name: 'Mushroom',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/71yvtWeeMoL._AC_UL320_.jpg',
        price: '₹65',
        link: 'https://www.amazon.in/s?k=mushroom',
    },
    {
        name: 'Peas',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/519pB8K1U2L._AC_UL320_.jpg',
        price: '₹70',
        link: 'https://www.amazon.in/s?k=peas',
    },
    {
        name: 'corn',
        category: 'Vegetables',
        image: 'https://www.jiomart.com/images/product/original/590001266/sweet-corn-1-pc-approx-250-g-450-g-product-images-o590001266-p590001266-0-202203170359.jpg?im=Resize=(360,360)',
        price: '₹75',
        link: 'https://www.amazon.in/s?k=corn',
    },
    {
        name: 'Okra (Bhendi)',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/51yvxGKCiYL._AC_UL320_.jpg',
        price: '₹80',
        link: 'https://www.amazon.in/s?k=okra',
    },
    {
        name: 'Brinjal',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/21hbs4DgbFL._AC_UL320_.jpg',
        price: '₹85',
        link: 'https://www.amazon.in/s?k=brinjal',
    },
    {
        name: 'Capsicum',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/41XX8wlWwEL._AC_UL320_.jpg',
        price: '₹90',
        link: 'https://www.amazon.in/s?k=capsicum',
    },
    {
        name: 'Bottle Gourd',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/51zEr2QHboS._AC_UL320_.jpg',
        price: '₹20',
        link: 'https://www.amazon.in/s?k=bottle-gourd',
    },
    {
        name: 'Bitter Gourd',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/813Ndvv+VDL._AC_UL320_.jpg',
        price: '₹25',
        link: 'https://www.amazon.in/s?k=bitter-gourd',
    },
    {
        name: 'Snake Gourd',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/516mALZi8HS._AC_UL320_.jpg',
        price: '₹30',
        link: 'https://www.amazon.in/s?k=snake-gourd',
    },
    {
        name: 'Ridge Gourd (Torai)',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/71AyB60h0CL._AC_UL320_.jpg',
        price: '₹35',
        link: 'https://www.amazon.in/s?k=ridge-gourd',
    },
    {
        name: 'Pointed Gourd',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/71QmZMugWNL._AC_UL320_.jpg',
        price: '₹40',
        link: 'https://www.amazon.in/s?k=pointed-gourd',
    },
    {
        name: 'Ash Gourd',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/61DPTZDBoQL._AC_UL320_.jpg',
        price: '₹45',
        link: 'https://www.amazon.in/s?k=ash-gourd',
    },
    {
        name: 'Round Gourd',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/412gK4WuiCL._AC_UL320_.jpg',
        price: '₹50',
        link: 'https://www.amazon.in/s?k=round-gourd',
    },
    {
        name: 'Cluster Beans',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/41ri+G81WUL._AC_UL320_.jpg',
        price: '₹60',
        link: 'https://www.amazon.in/s?k=cluster-beans',
    },
    {
        name: 'Broad Beans (Avare Chikadi',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/71YrgJZmqAL._AC_UL320_.jpg',
        price: '₹65',
        link: 'https://www.amazon.in/s?k=broad-beans',
    },
    {
        name: 'Green Chilli',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/71wSmRYcF4L._AC_UL320_.jpg',
        price: '₹75',
        link: 'https://www.amazon.in/s?k=green-chilli',
    },
    {
        name: 'Red Chilli',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/61nf90lbP3L._AC_UL640_QL65_.jpg',
        price: '₹80',
        link: 'https://www.amazon.in/s?k=red-chilli',
    },
    {
        name: 'Turnip',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/51VzNmmZ9IL._AC_UL320_.jpg',
        price: '₹45',
        link: 'https://www.amazon.in/s?k=turnip',
    },
    {
        name: 'Pumpkin',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/41vLyzo442L._AC_UL320_.jpg',
        price: '₹55',
        link: 'https://www.amazon.in/s?k=pumpkin',
    },
    {
        name: 'Red Spinach',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/51SsNYLXCfS._AC_UL320_.jpg',
        price: '₹85',
        link: 'https://www.amazon.in/s?k=red-spinach',
    },
    {
        name: 'Watercress',
        category: 'Vegetables',
        image: 'https://m.media-amazon.com/images/I/51c919ZUfvL._AC_UL320_.jpg',
        price: '₹90',
        link: 'https://www.amazon.in/s?k=watercress',
    },
    {
        name: 'Apple',
        category: 'Fruits',
        image: 'https://m.media-amazon.com/images/I/41frXJCfJ4L.jpg',
        price: '₹50',
        link: 'https://www.amazon.in/Fresh-Apple-Royal-Gala-Pieces/dp/B07HN2KWHZ/ref=sr_1_4_f3_0o_fs?dib=eyJ2IjoiMSJ9.iG14Bj6BH8jlBf2PVo3hw8iSNdIwLJTCh81_S9PyUtHnrXfvd4vRscoPZSFFqEzlOD9tLi6dyqmde8dS7Fiot3SYOLLAqLiUl0jr3yrcmQalX2orS56VzFy82_pGIWtMj5EJ1GtD-LTBxOO2q9Z8iWhk_uXQrgfVU6LnZcllU0IA3w_ylR0pbjUgncD8cL6mXTPfvtoSPVTj3iNUwRu7CxotmLh4bhjUVpp8WIu1HOQ.cxrXvtG8rx78V9QgypGjXUGXif7QEAKYPVHNLbXmS2o&dib_tag=se&keywords=apple&qid=1725724425&sr=8-4e',
      },
      {
        name: 'Banana',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/1c/16/62/1c1662f546cc85a1d77732c840ff9113.jpg',
        price: '₹20',
        link: 'https://www.amazon.in/s?k=banana',
      },
      {
        name: 'Mango',
        category: 'Fruits',
        image: 'https://m.media-amazon.com/images/I/51ByzL4LRML._AC_UL320_.jpg',
        price: '₹60',
        link: 'https://www.amazon.in/s?k=mango',
      },
      {
        name: 'Orange',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/7a/aa/a5/7aaaa545e00e8a434850e80b8910dd94.jpg',
        price: '₹40',
        link: 'https://www.amazon.in/s?k=orange',
      },
      {
        name: 'Grapes',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/7a/38/e7/7a38e7207389f22a6a27f4e095807792.jpg',
        price: '₹80',
        link: 'https://www.amazon.in/s?k=grapes',
      },
      {
        name: 'Pineapple',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/8b/f2/8e/8bf28e6b9a718175dd44a8e5103c1cae.jpg',
        price: '₹100',
        link: 'https://www.amazon.in/s?k=pineapple',
      },
      {
        name: 'Watermelon',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/1e/a7/a9/1ea7a9f76ef5487ed6f0e04286a48126.jpg',
        price: '₹120',
        link: 'https://www.amazon.in/s?k=watermelon',
      },
      {
        name: 'Peach',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/62/1b/1d/621b1d270d5595c42cdf90976384b758.jpg',
        price: '₹90',
        link: 'https://www.amazon.in/s?k=peach',
      },
      {
        name: 'Cherry',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/19/da/ee/19daee30c66a71b04b2fe40d13bb419f.jpg',
        price: '₹110',
        link: 'https://www.amazon.in/s?k=cherry',
      },
      {
        name: 'Plum',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/43/86/25/43862549c42b44c3ceab28af20099998.jpg',
        price: '₹130',
        link: 'https://www.amazon.in/s?k=plum',
      },
      {
        name: 'Kiwi',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/79/99/70/799970f50080ee196cc337fb2843ceb8.jpg',
        price: '₹140',
        link: 'https://www.amazon.in/s?k=kiwi',
      },
      {
        name: 'Blueberry',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/9a/fc/f8/9afcf801d80666190af97ff4413e2b43.jpg',
        price: '₹150',
        link: 'https://www.amazon.in/s?k=blueberry',
      },
      {
        name: 'Strawberry',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/ab/f2/2a/abf22a98ff43ed9d1e2514d00915dd30.jpg',
        price: '₹160',
        link: 'https://www.amazon.in/s?k=strawberry',
      },
      {
        name: 'Raspberry',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/26/f6/36/26f636ddd9bd6d1436e734a6455a21bb.jpg',
        price: '₹170',
        link: 'https://www.amazon.in/s?k=raspberry',
      },
      {
        name: 'Blackberry',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/75/d3/e7/75d3e79388f3a1a7723050083bcdcd7b.jpg',
        price: '₹180',
        link: 'https://www.amazon.in/s?k=blackberry',
      },
      {
        name: 'Guava',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/46/84/1a/46841a9283d59469e89356c2024f687b.jpg',
        price: '₹40',
        link: 'https://www.amazon.in/s?k=guava',
      },
      {
        name: 'Papaya',
        category: 'Fruits',
        image: 'https://i.pinimg.com/564x/f1/95/9a/f1959ab5bd7597786840e9b0856a0d98.jpg',
        price: '₹50',
        link: 'https://www.amazon.in/s?k=papaya',
      },
      {
        name: 'Pomegranate',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/c2/b1/09/c2b10932d82f89d8f044556b5e0f1f53.jpg',
        price: '₹80',
        link: 'https://www.amazon.in/s?k=pomegranate',
      },
      {
        name: 'Jackfruit',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/07/95/66/079566be3fbc1bd72cf20484d86b3bac.jpg',
        price: '₹90',
        link: 'https://www.amazon.in/s?k=jackfruit',
      },
      {
        name: 'Dragon Fruit',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/04/71/fd/0471fd0da408b5a66cb084261675b907.jpg',
        price: '₹100',
        link: 'https://www.amazon.in/s?k=dragon-fruit',
      },
      {
        name: 'Starfruit',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/59/0d/fe/590dfe5e055a94d526057e90d92dca41.jpg',
        price: '₹120',
        link: 'https://www.amazon.in/s?k=starfruit',
      },
      {
        name: 'Custard Apple',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/fc/7c/7d/fc7c7d333b7ca890ec90a82ddaee77f5.jpg',
        price: '₹40',
        link: 'https://www.amazon.in/s?k=custard-apple',
      },
      {
        name: 'Chikoo',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/38/c3/25/38c3253efeaa10d293ec1b7d4cc81787.jpg',
        price: '₹60',
        link: 'https://www.amazon.in/s?k=chikoo',
      },
      {
        name: 'Jamun',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/52/c9/3e/52c93e8924576afa78563d217e21da38.jpg',
        price: '₹70',
        link: 'https://www.amazon.in/s?k=jamun',
      },
      {
        name: 'Litchi',
        category: 'Fruits',
        image: 'https://i.pinimg.com/236x/da/d7/df/dad7dfcd90ca8a4f798194a4585cb271.jpg',
        price: '₹130',
        link: 'https://www.amazon.in/s?k=litchi',
      },
    // Add more products as needed
];